accent = "#B38A58"
cursor = "#B38A58"
foreground = "#3C5233"
background = "#0D1F22"
selection_foreground = "#0D1F22"
selection_background = "#B38A58"
color0 = "#0D1F22"
color1 = "#6F732F"
color2 = "#264027"
color3 = "#B38A58"
color4 = "#3C5233"
color5 = "#6F732F"
color6 = "#264027"
color7 = "#3C5233"
color8 = "#264027"
color9 = "#8FA641"
color10 = "#3C5233"
color11 = "#D4A870"
color12 = "#4E6A44"
color13 = "#8FA641"
color14 = "#3C5233"
color15 = "#B38A58"